#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
#
# SPDX-License-Identifier: GPL-3.0-or-later

usage()
{
    cat <<-EndUsage
		pull: Git pull the repo
	EndUsage
    exit 1
}

t_pull()
{
    git -C "$TODO_DIR" pull
}

while [ -n "${1}" ]
do
    case "$1" in
        -d|--debug)
            set -x
        ;;
        -e|--error)
            set -e
        ;;
        usage)
            usage
        ;;
        pull)
            t_pull
        ;;
        *)
            echo $1 not found
        ;;
    esac
    shift
done
