#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
#
# SPDX-License-Identifier: GPL-3.0-or-later

usage()
{
    cat <<-EndUsage
		push: Add, commit and push the new changes to the Git repo.
	EndUsage
    exit 1
}

t_push()
{
    if [ -n "$(git -C $TODO_DIR status --porcelain)" ]
    then
        git -C "$TODO_DIR" add --all
        git -C "$TODO_DIR" commit -m "auto-update"
        git -C "$TODO_DIR" push
    fi
}

while [ -n "${1}" ]
do
    case "$1" in
        -d|--debug)
            set -x
        ;;
        -e|--error)
            set -e
        ;;
        usage)
            usage
        ;;
        push)
            t_push
        ;;
        *)
            echo $1 not found
        ;;
    esac
    shift
done
